@extends('app')

@section('title'){{'Povijest'}}@stop

@section('content')
<header class="pages-header">
	<div class="container">
		<div class="flex-container">
			<div class='title'>
				<h1><a href="{{ route('pages.povijest') }}"><span class="glyphicon glyphicon-calendar"></span> Povijest udruge</a></h1>
			</div>
		</div>
	</div>
</header>
<div class="container">
<p style='text-align:justify'>Udruga studenata Međimurja osnovana je <strong>19. listopada 2011.</strong> godine u Međimurskom Domu u Zagrebu na konstituirajućoj sjednici Udruge. Stara udruga koja je okupljala studente iz Međimurja – "Klub studenata Međimurja" prestala s radom, a razlog tome je bila neaktivnost vodstva koje je završilo svoje fakultetsko obrazovanje, te je Klub obrisan iz registra udruga. Tako je došlo do potrebe osnivanja nove udruge koja će ponovno okupiti međimurske studente. Osnivačkoj sjednici odazvali su se mnogobrojni studenti i simpatizeri. Usvojen je novi Statut Udruge, izglasano je predsjedništvo, nadzorni odbor i tajnik Udruge, na period od jedne akademske godine. Za prvog predsjednika Udruge izabran je <strong>Igor Ivković</strong>, a njegovi podpredsjednici su bili Karolina Kolarić i Benjamin Štampar.  Predsjedništvo su činili Sanela Horvatić, Ivan Borović, Matko Lovrec, Igor Ivković, Karolina Kolarić, Benjamin Štampar, Luka Štruc, Vedran Babić i Vedran Blagus. Za glavnog tajnika Udruge izabran je Deni Oreški. U Nadzorni odbor odabrani su Luka Vlahek, Mateja Vuk, Hrvoje Cirković, David Ivković te Alexandra Bedić. Udruga studenata Međimurja tada je bila smještena u prostorijama Zavičajnog društva Međimurja u Zagrebu, na adresi Ilica 10. Vodstvo je od samog početka ozbiljno i marljivo krenulo s organizacijom i kvalitetnim radom. Organizirali su nekoliko događaja koji su danas postali prepoznatljiva tradicija Udruge studenata Međimurja, poput "Kam na faks"i Međimurske fešte. Povezali su se s drugim studentskim udrugama, te sudjelovali na mnogim manifestacijama diljem Hrvatske koje su organizirane na razini sveučilišta i udruga. Članovi Udruge studenata Međimurja hodočastili su na Mariju Bistricu, sudjelovali u studentskom mimohodu u Vukovaru i na Humanijadi, organizirali nekoliko međimurskih druženja i zabava. Tijekom akademske godine 2011./2012. završen je proces registracije Udruge, izabran je logo i pokrenuta je internetska stranica Udruge.</p>
<a target='_blank' href="{{ asset('img/udruga/pov01.JPG') }}" data-lightbox="pov"><img src="{{ asset('img/udruga/pov01.JPG') }}" class="img-responsive img-rounded" style="max-height:400px; margin:20px auto"></a>
<p style='text-align:justify'>Na početku akademske godine 2012./2013. održana je nova godišnja skupština Udruge na kojoj su se vodstvo i članovi osvrnuli na uspješnu prvu godinu rada, te je odabrano novo vodstvo. Za novog predsjednika jednoglasno je izabran <strong>Deni Oreški</strong>, dosadašnji tajnik Udruge. Također je izabrano i novo predsjedništvo u sastavu: Benjamin Štampar, Karolina Kolarić, Ivan Borović, David Ivković, Hrvoje Cirković, Elena Govedić, Elena Ružić i Matko Lovrec.  U Nadzorni odbor Udruge izabrani su Vedran Babić, Kris Oliver Jalušić, Luka Vlahek, Matija Hranilović te Katja Turk. Za novog tajnika Udruge izabran je Vanja Ovčar,  a za blagajnicu Tihana Srpak. Osim što su vodstvo i članovi Udruge uspješno proveli projekate "Kam na faks" i "Međimurska fešta", sudjelovali su i na sajmu studentskih udruga Hrvatske "Tko smo? Što smo? Odakle smo?" na kojoj su predstavili prisutnim običaje i delikatese Međimurske županije.  Sudjelovali su i na nekoliko hodočašća, druženja, a započelo se dodjeljivanjem stipendija. Dodijeljene su dvije stipendije, jedna na temelju akademskog uspjeha i jedna na temelju socijalnog statusa.</p>
<a target='_blank' href="{{ asset('img/udruga/pov02.JPG') }}" data-lightbox="pov"><img src="{{ asset('img/udruga/pov02.JPG') }}" class="img-responsive img-rounded" style="max-height:400px; margin:20px auto"></a>
<p style='text-align:justify'>U akademskoj godini 2013./2014. za predsjednika Udruge je izabran <strong>Luka Vlahek</strong>, a njegove zamjenice su bile Karolina Kolarić i Elena Ružić. Predsjedništvo su činili David Ivković, Hrvoje Cirković, Elena Govedić, Matija Kikelj, Antonio Sermek i Matija Sabolek. Nadzorni odbor se sastojao od 5 članova, s to su bili Matko Lovrec, David Krištofić, Ivan Borović, Magdalena Trstenjak i Kris Oliver Jalušić. Za tajnicu Udruge ponovno je izabrana Tihana Srpak. Od novih projekata, započelo se s organizacijom dvodnevnog putovanja kroz Međimursku županiju pod nazivom "Upoznajmo Međimurje". Udruga studenata Međimurja svojom aktivnošću postala je jedna od najaktivnijih studentskih udruga.</p>
<a target='_blank' href="{{ asset('img/udruga/pov03.jpg') }}" data-lightbox="pov"><img src="{{ asset('img/udruga/pov03.jpg') }}" class="img-responsive img-rounded" style="max-height:400px; margin:20px auto"></a>
<p style='text-align:justify'>Četvrti sastav Predsjedništva činili su David Krištofić, Karolina Kolarić, Antonio Sermek, Matko Lovrec, Elena Govedić, David Ivković, Matija Kikelj, Matija Sabolek, Luka Vlahek, a za predsjednika je izabran <strong>David Krištofić</strong>. Zamjenici predsjednika bili su Karolina Kolarić i Antonio Sermek, a izabran je i novi Nadzorni odbor u sastavu Marija Repalust, Nikola Sršan, Iva Ivković, Karlo Radmanić, Tajana Pavlic. Na mjestu tajnika Udruge je nastavila s radom Tihana Srpak. Novo predsjedništvo nastavilo je s organiziranjem Međimurskih fešti i ponovno je pokrenulo projekt "Kam na faks" koji je prošao vrlo uspješno, te okupio velik broj studenata i maturanata. Uspjeli su privući studente s područja cijele Hrvatske i pokazati im običaje i krajolik zavičaja organiziranjem projekta "Upoznajmo Međimurje". Na samom kraju mandata ovog sastava Udruga se preselila u nove prostorije koje im je ustupilo na korištenje Zavičajno društvo Međimuraca u Gajevoj 2A, gdje su na početku akademske godine 2015./ 2016. pripremili druženje posvećeno brucošima, s ciljem da ih što bolje pripreme za studentske dane i požele toplu dobrodošlicu.</p>
<a target='_blank' href="{{ asset('img/udruga/pov04.jpg') }}" data-lightbox="pov"><img src="{{ asset('img/udruga/pov04.jpg') }}" class="img-responsive img-rounded" style="max-height:400px; margin:20px auto"></a>
</div>
@stop